import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'
import { api } from './api'
import type { SystemStatus, TemplateRecord } from './api'

const navItems = ['Dashboard', 'Conversations', 'Campaigns', 'Contacts', 'Escalations', 'Templates', 'Knowledge', 'Settings']
const contacts = [
  { name: 'Amina Rahman', phone: '+92 300 812 4432', status: 'Opted in', last: '2 min ago', tag: 'VIP' },
  { name: 'Bilal Khan', phone: '+92 321 744 1082', status: 'Opted in', last: '18 min ago', tag: 'Lead' },
  { name: 'Sana Ahmed', phone: '+92 333 192 8841', status: 'Paused', last: 'Yesterday', tag: 'Support' },
  { name: 'Omar Farooq', phone: '+92 312 655 7200', status: 'Opted out', last: 'Aug 31', tag: 'Customer' },
]
const conversations = [
  { name: 'Amina Rahman', preview: 'Can I change my appointment time?', time: '2 min', unread: 2, intent: 'Appointment' },
  { name: 'Bilal Khan', preview: 'Thank you, that helped a lot.', time: '18 min', unread: 0, intent: 'Resolved' },
  { name: 'Sana Ahmed', preview: 'I need to speak with someone.', time: '42 min', unread: 1, intent: 'Escalated' },
  { name: 'Hassan Ali', preview: 'What are your opening hours?', time: '1 hr', unread: 0, intent: 'FAQ' },
]
type Campaign = { name: string; status: string; sent: number; delivered: number; failed: number; template: string; start: string }
const campaigns: Campaign[] = [
  { name: 'Summer Promo', status: 'Running', sent: 1824, delivered: 1675, failed: 32, template: 'summer_offer_v2', start: 'Today, 10:00 AM' },
  { name: 'Appointment Reminder', status: 'Scheduled', sent: 960, delivered: 912, failed: 11, template: 'appointment_followup', start: 'Tomorrow, 09:00 AM' },
  { name: 'Welcome Flow', status: 'Completed', sent: 420, delivered: 398, failed: 4, template: 'welcome_sequence', start: 'Last week' },
]
type MessageTemplate = { id: number | string; name: string; category: string; language: string; status: string; body: string }
const defaultTemplates: MessageTemplate[] = [
  { id: 'summer_offer_v2', name: 'summer_offer_v2', category: 'Marketing', language: 'English', status: 'Approved', body: 'Hi {{first_name}}, enjoy {{offer_name}} until {{expiry_date}}.' },
  { id: 'appointment_followup', name: 'appointment_followup', category: 'Utility', language: 'English', status: 'Approved', body: 'Hi {{first_name}}, this is a reminder for your appointment.' },
  { id: 'welcome_sequence', name: 'welcome_sequence', category: 'Marketing', language: 'English', status: 'Pending review', body: 'Welcome, {{first_name}}. We are happy to have you with us.' },
]

function Login({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState('operator@business.com')
  const [password, setPassword] = useState('password')
  const submit = (event: FormEvent) => { event.preventDefault(); if (email && password) onLogin() }
  return <main className="login-page"><div className="login-art"><div className="brand-mark large">W</div><p className="eyebrow">WhatsApp Bot</p><h1>Conversations that keep moving.</h1><p>Manage campaigns, customer replies, and the moments that need a human touch.</p><div className="login-art-footer"><span className="status-dot" /> All systems operational</div></div><form className="login-card" onSubmit={submit}><span className="eyebrow">Operations Console</span><h2>Welcome back</h2><p className="muted">Sign in to manage your WhatsApp business inbox.</p><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="primary-button full-width-button">Sign in</button><small className="muted">Demo access is enabled for this local prototype.</small></form></main>
}

function App() {
  const [authenticated, setAuthenticated] = useState(false)
  const [selectedNav, setSelectedNav] = useState('Dashboard')
  const [systemStatus, setSystemStatus] = useState<SystemStatus | null>(null)
  const [apiNotice, setApiNotice] = useState('')

  useEffect(() => {
    if (!authenticated) return
    api.getStatus().then(setSystemStatus).catch(() => setApiNotice('Backend unavailable; showing demo data.'))
  }, [authenticated])

  if (!authenticated) return <Login onLogin={() => setAuthenticated(true)} />
  const page = selectedNav === 'Conversations' ? <Inbox /> : selectedNav === 'Contacts' ? <Contacts /> : selectedNav === 'Escalations' ? <Escalations /> : selectedNav === 'Templates' ? <Templates /> : selectedNav === 'Knowledge' ? <Knowledge /> : selectedNav === 'Settings' ? <Settings /> : selectedNav === 'Campaigns' ? <Campaigns /> : <Dashboard status={systemStatus} />
  const toggleBot = () => (systemStatus?.bot.globally_paused ? api.resumeBot() : api.pauseBot()).then(() => api.getStatus()).then(setSystemStatus).catch(() => setApiNotice('Could not update bot status.'))
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">W</div><div><strong>WhatsApp Bot</strong><span>{systemStatus?.business.name ?? 'Operations Console'}</span></div></div><nav className="nav">{navItems.map((item) => <button key={item} className={selectedNav === item ? 'nav-item active' : 'nav-item'} onClick={() => setSelectedNav(item)}><span className="nav-icon">{item.slice(0, 1)}</span>{item}</button>)}</nav><div className="sidebar-card"><span className="label">Bot status</span><div className="status-row"><span className="status-dot" />{systemStatus?.bot.globally_paused ? 'Paused' : 'Online'}</div><small>{systemStatus ? `${systemStatus.metrics_summary.open_escalations} open escalations` : 'Connecting to backend...'}</small><button className="sidebar-action" onClick={toggleBot}>{systemStatus?.bot.globally_paused ? 'Resume bot' : 'Pause bot'}</button></div></aside><main className="main-panel"><header className="topbar"><div><p className="eyebrow">{selectedNav === 'Dashboard' ? 'Good morning, operator' : 'Workspace / ' + selectedNav}</p><h1>{selectedNav}</h1></div><div className="topbar-actions"><button className="icon-button" title="Notifications">Bell</button><button className="avatar-button" title="Sign out" onClick={() => setAuthenticated(false)}>OP</button></div></header>{apiNotice && <div className="api-notice">{apiNotice}</div>}{page}</main></div>
}

function Dashboard({ status }: { status: SystemStatus | null }) { return <><section className="stats-row"><Stat label="Messages today" value="2,846" trend="+18.2%" /><Stat label="Open conversations" value="184" trend="12 waiting" /><Stat label="Campaign delivery" value="92.4%" trend="+2.1%" /><Stat label="Escalations" value={String(status?.metrics_summary.open_escalations ?? 16)} trend="Live from API" /></section><div className="content-grid"><section className="panel wide-panel"><PanelHeader title="Activity overview" action="Last 7 days" /><div className="chart"><div className="chart-bars">{[42, 58, 48, 72, 64, 86, 78].map((height, index) => <div className="bar-wrap" key={height}><div className="bar" style={{ height: `${height}%` }} /><small>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][index]}</small></div>)}</div></div></section><section className="panel"><PanelHeader title="Needs attention" action="View queue" /><div className="attention-list"><Attention title={`${status?.metrics_summary.open_escalations ?? 4} open escalations`} detail="Customers waiting for a human reply" tone="urgent" /><Attention title={`${status?.metrics_summary.total_suppressed ?? 12} suppressed contacts`} detail="Review consent status before sending" tone="warning" /><Attention title="Campaign ready" detail="Summer Promo has 1,982 eligible recipients" tone="ok" /></div></section></div><section className="panel"><PanelHeader title="Recent conversations" action="Open inbox" /><div className="table-list">{conversations.slice(0, 3).map((conversation) => <div className="table-row" key={conversation.name}><div className="person"><span className="avatar">{conversation.name.slice(0, 1)}</span><div><strong>{conversation.name}</strong><small>{conversation.preview}</small></div></div><span className="muted">{conversation.time} ago</span><span className="status-pill neutral">{conversation.intent}</span></div>)}</div></section></> }

function Campaigns() { const [sent, setSent] = useState(false); return <><section className="stats-row"><Stat label="Eligible recipients" value="48,360" trend="Ready to send" /><Stat label="Queued" value="12,900" trend="3 campaigns" /><Stat label="Delivery rate" value="92.4%" trend="Healthy" /><Stat label="Failure threshold" value="2.5%" trend="Compliance guard" /></section><div className="content-grid campaign-grid"><section className="panel wide-panel"><PanelHeader title="Campaign setup" action="Preview" /><div className="form-grid"><label>Campaign name<input defaultValue="Summer Promo" /></label><label>Template<select defaultValue="summer_offer_v2"><option>summer_offer_v2</option><option>appointment_followup</option><option>welcome_sequence</option></select></label><label>Language<select defaultValue="English"><option>English</option><option>Arabic</option></select></label><label>Schedule<input defaultValue="Today, 10:00 AM" /></label><label className="full-width">Recipient CSV<div className="upload-box"><input type="file" /><span>Choose recipient file</span></div></label><label className="full-width">Template variables<textarea defaultValue="first_name, offer_name, expiry_date" rows={3} /></label></div><div className="form-actions"><button className="ghost-button" onClick={() => setSent(true)}>Dry run</button><button className="primary-button" onClick={() => setSent(true)}>Send now</button></div>{sent && <div className="inline-success">Campaign validated. 1,982 recipients are eligible.</div>}</section><section className="panel"><PanelHeader title="Send summary" /><div className="summary-box"><div><span>Selected</span><strong>2,340</strong></div><div><span>Eligible</span><strong>1,982</strong></div><div><span>Rejected</span><strong>358</strong></div></div><ul className="reason-list"><li>Opt-out: 121</li><li>Suppressed: 58</li><li>Missing phone: 14</li><li>Quiet hours: 42</li></ul></section></div><section className="panel"><PanelHeader title="Recent campaigns" action="All campaigns" /><div className="campaign-list">{campaigns.map((campaign) => <div className="campaign-row-card" key={campaign.name}><div className="campaign-main"><div><strong>{campaign.name}</strong><small>{campaign.template}</small></div><span className={`status-pill ${campaign.status.toLowerCase()}`}>{campaign.status}</span></div><div className="campaign-metrics"><span>{campaign.sent} sent</span><span>{campaign.delivered} delivered</span><span>{campaign.failed} failed</span></div><div className="campaign-foot"><small>Started: {campaign.start}</small><button className="ghost-button small">View</button></div></div>)}</div></section></> }

function Inbox() { const [selected, setSelected] = useState(conversations[0]); return <div className="inbox-layout"><section className="panel conversation-list"><PanelHeader title="Inbox" action="Filter" /><input placeholder="Search conversations" />{conversations.map((conversation) => <button className={selected.name === conversation.name ? 'conversation active' : 'conversation'} key={conversation.name} onClick={() => setSelected(conversation)}><span className="avatar">{conversation.name[0]}</span><span className="conversation-copy"><strong>{conversation.name}</strong><small>{conversation.preview}</small></span><span className="conversation-meta"><small>{conversation.time}</small>{conversation.unread > 0 && <b>{conversation.unread}</b>}</span></button>)}</section><section className="panel chat-panel"><div className="chat-header"><div className="person"><span className="avatar">{selected.name[0]}</span><div><strong>{selected.name}</strong><small>Online via WhatsApp</small></div></div><span className="status-pill neutral">{selected.intent}</span></div><div className="messages"><div className="message received">Hi, I need help with my booking.</div><div className="message sent">Of course. I can help with that. What would you like to change?</div><div className="message received">{selected.preview}</div></div><div className="composer"><input placeholder="Write a reply..." /><button className="primary-button">Send</button></div></section></div> }
function Contacts() { return <section className="panel"><PanelHeader title="Contact directory" action="Import CSV" /><div className="toolbar"><input placeholder="Search by name or phone" /><select><option>All consent states</option><option>Opted in</option><option>Paused</option><option>Opted out</option></select><button className="primary-button">Add contact</button></div><div className="table-list">{contacts.map((contact) => <div className="table-row" key={contact.phone}><div className="person"><span className="avatar">{contact.name[0]}</span><div><strong>{contact.name}</strong><small>{contact.phone}</small></div></div><span className="status-pill neutral">{contact.tag}</span><span className={`status-pill ${contact.status === 'Opted in' ? 'completed' : 'paused'}`}>{contact.status}</span><span className="muted">{contact.last}</span></div>)}</div></section> }
function Escalations() {
  const [items, setItems] = useState<import('./api').Escalation[]>([])
  const [notice, setNotice] = useState('')
  useEffect(() => { api.getEscalations().then(setItems).catch(() => setNotice('Backend unavailable; showing demo queue.')) }, [])
  const act = (id: number, resolve: boolean) => (resolve ? api.resolveEscalation(id, 'Resolved by operator') : api.acknowledgeEscalation(id)).then(() => api.getEscalations()).then(setItems).catch(() => setNotice('Could not update escalation.'))
  return <section className="panel"><PanelHeader title="Escalation queue" action="All statuses" />{notice && <div className="api-notice">{notice}</div>}{items.length === 0 ? <div className="queue-list"><Attention title="Sana Ahmed needs a human reply" detail="Demo queue · 42 min ago" tone="urgent" /><Attention title="Refund request from Farah Noor" detail="Demo queue · 1 hr ago" tone="warning" /><Attention title="Language handoff: Ahmed Raza" detail="Demo queue · 3 hrs ago" tone="ok" /></div> : <div className="live-queue">{items.map((item) => <div className="live-escalation" key={item.id}><div><strong>{item.summary || item.reason}</strong><small>{item.detected_intent || 'Escalation'} · {new Date(item.created_at).toLocaleString()}</small></div><div className="queue-actions"><button className="ghost-button small" onClick={() => act(item.id, false)}>Acknowledge</button><button className="primary-button small" onClick={() => act(item.id, true)}>Resolve</button></div></div>)}</div>}</section>
}
function Templates() {
  const [templates, setTemplates] = useState<MessageTemplate[]>(() => {
    try { return JSON.parse(localStorage.getItem('whatsapp-bot-templates') ?? 'null') ?? defaultTemplates } catch { return defaultTemplates }
  })
  const [editing, setEditing] = useState<MessageTemplate | null>(null)
  const [notice, setNotice] = useState('')
  const [usingBackend, setUsingBackend] = useState(false)
  useEffect(() => {
    api.getTemplates().then((records) => { setTemplates(records.map(fromApiTemplate)); setUsingBackend(true) }).catch(() => setNotice('Backend unavailable; using local templates until it reconnects.'))
  }, [])
  const saveTemplates = (next: MessageTemplate[]) => { setTemplates(next); localStorage.setItem('whatsapp-bot-templates', JSON.stringify(next)) }
  const startNew = () => setEditing({ id: crypto.randomUUID(), name: '', category: 'Marketing', language: 'en', status: 'PENDING', body: '' })
  const save = async (template: MessageTemplate) => {
    if (!template.name.trim() || !template.body.trim()) { setNotice('Template name and message body are required.'); return }
    const payload = toApiTemplate(template)
    try {
      const saved = usingBackend && typeof template.id === 'number' ? await api.updateTemplate(template.id, payload) : await api.createTemplate(payload)
      const next = templates.some((item) => item.id === template.id) ? templates.map((item) => item.id === template.id ? fromApiTemplate(saved) : item) : [fromApiTemplate(saved), ...templates]
      saveTemplates(next); setUsingBackend(true); setEditing(null); setNotice('Template saved to the backend.')
    } catch { setNotice('Could not save to backend; template was saved locally.'); const next = templates.some((item) => item.id === template.id) ? templates.map((item) => item.id === template.id ? template : item) : [template, ...templates]; saveTemplates(next); setEditing(null) }
  }
  const remove = async (id: number | string) => { try { if (usingBackend && typeof id === 'number') await api.deleteTemplate(id); setNotice('Template deleted from the backend.') } catch { setNotice('Could not delete from backend; removed locally.') } saveTemplates(templates.filter((item) => item.id !== id)); if (editing?.id === id) setEditing(null) }
  return <section className="panel"><PanelHeader title="Message templates" action="Create template" />{notice && <div className="api-notice">{notice}</div>}<div className="template-toolbar"><span className="muted">{templates.length} templates · {usingBackend ? 'Saved on backend' : 'Local fallback'}</span><button className="primary-button" onClick={startNew}>Add template</button></div>{editing && <TemplateEditor template={editing} onSave={save} onCancel={() => setEditing(null)} />}<div className="template-grid">{templates.map((template) => <div className="template-card" key={template.id}><div className="template-icon">T</div><div className="template-card-copy"><strong>{template.name || 'Untitled template'}</strong><small>{displayCategory(template.category)} · {template.language} · {displayStatus(template.status)}</small><p>{template.body}</p></div><div className="template-card-actions"><button className="link-button" onClick={() => setEditing(template)}>Edit</button><button className="danger-button" onClick={() => remove(template.id)}>Delete</button></div></div>)}</div></section>
}
function fromApiTemplate(template: TemplateRecord): MessageTemplate { return { id: template.id, name: template.name, category: template.category, language: template.language, status: template.status, body: template.body } }
function toApiTemplate(template: MessageTemplate): Omit<TemplateRecord, 'id' | 'created_at' | 'updated_at'> { return { name: template.name.trim(), language: template.language.toLowerCase().slice(0, 16), category: template.category.toUpperCase(), status: template.status.toUpperCase(), body: template.body.trim(), purpose: null, requires_opt_in: template.category.toUpperCase() === 'MARKETING', variables: [] } }
function displayCategory(value: string) { return value.charAt(0) + value.slice(1).toLowerCase() }
function displayStatus(value: string) { return value.replace('_', ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()) }
function TemplateEditor({ template, onSave, onCancel }: { template: MessageTemplate; onSave: (template: MessageTemplate) => void; onCancel: () => void }) {
  const [draft, setDraft] = useState(template)
  const update = (field: keyof MessageTemplate, value: string) => setDraft({ ...draft, [field]: value })
  return <div className="template-editor"><div className="panel-header"><h2>{template.name ? 'Edit template' : 'New template'}</h2><button className="link-button" onClick={onCancel}>Cancel</button></div><div className="form-grid"><label>Template name<input value={draft.name} placeholder="appointment_reminder" onChange={(event) => update('name', event.target.value)} /></label><label>Category<select value={draft.category.toUpperCase()} onChange={(event) => update('category', event.target.value)}><option value="MARKETING">Marketing</option><option value="UTILITY">Utility</option><option value="AUTHENTICATION">Authentication</option></select></label><label>Language<select value={draft.language.toLowerCase()} onChange={(event) => update('language', event.target.value)}><option value="en">English</option><option value="ar">Arabic</option><option value="ur">Urdu</option></select></label><label>Status<select value={draft.status.toUpperCase()} onChange={(event) => update('status', event.target.value)}><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="PAUSED">Paused</option><option value="REJECTED">Rejected</option></select></label><label className="full-width">Message body<textarea rows={5} value={draft.body} placeholder="Hi {{first_name}}, ..." onChange={(event) => update('body', event.target.value)} /></label></div><div className="form-actions"><button className="ghost-button" onClick={onCancel}>Cancel</button><button className="primary-button" onClick={() => onSave(draft)}>Save template</button></div></div>
}
function Knowledge() { return <section className="panel"><PanelHeader title="Knowledge base" action="Add article" /><div className="knowledge-list"><div><strong>Aftercare instructions</strong><small>12 articles · Updated today</small></div><div><strong>Appointments and booking</strong><small>8 articles · Updated yesterday</small></div><div><strong>Returns and refunds</strong><small>6 articles · Updated Aug 28</small></div></div></section> }
function Settings() { return <section className="panel settings-panel"><PanelHeader title="Workspace settings" action="Save changes" /><label>Business name<input defaultValue="KhadijaF Business" /></label><label>Default language<select defaultValue="English"><option>English</option><option>Arabic</option></select></label><label>Quiet hours<input defaultValue="10:00 PM - 08:00 AM" /></label><label className="toggle-row"><input type="checkbox" defaultChecked /> Pause bot globally during maintenance</label></section> }
function Stat({ label, value, trend }: { label: string; value: string; trend: string }) { return <div className="stat-box"><span>{label}</span><strong>{value}</strong><small className="trend">{trend}</small></div> }
function PanelHeader({ title, action }: { title: string; action?: string }) { return <div className="panel-header"><h2>{title}</h2>{action && <button className="link-button">{action}</button>}</div> }
function Attention({ title, detail, tone }: { title: string; detail: string; tone: string }) { return <div className="attention-row"><span className={`attention-dot ${tone}`} /><div><strong>{title}</strong><small>{detail}</small></div><span className="arrow">›</span></div> }
export default App
